### PR TITLE
Move workspace to separate module

### LINKED ISSUE #114: Move Workspace to separate Workspace module
Move Workspace to separate Workspace module

### PR DESCRIPTION
**Pull request by haiodo**
1. Move workspace to separate module
2. Mongo - remove MongoConnection
3. Server - use workspace
4. tools - user workspace

Closes #114 

Signed-off-by: Andrey Sobolev <haiodo@gmail.com>

### CODE REVIEW

**Comment by z2sx** [comment]
Why (3) server use workspace?

**Comment by haiodo** [comment]
@z2sx server host access to `workspace`, I'm not sure how it could not use it.

**Comment by z2sx** [comment]
> @z2sx server host access to `workspace`, I'm not sure how it could not use it.

Can you please elaborate, what does it mean "server host access to workspace"?

**Comment by haiodo** [comment]
image

**Comment by z2sx** [comment]
OK, so then what is `workspace` responsibility? I was thinking it's for workspace creation, delete, etc.

**Comment by haiodo** [comment]
It for raw/insecure access to all workspace data, it hide how data is hold, different DBs, etc. So it allow to 'find' and 'tx' on workspace. 

For create/init we just need to send our transactions to workspace. 

To upgrade we will need both.

And it has cleanup method(name is question to discuss) to remove all data.

**Pull request merged**
